<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HuddleBoard.Playbook</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
  </ItemGroup>
</Project>
