namespace HuddleBoard.Playbook;

/// <summary>
/// Where the repository is, found by walking up from wherever the build tool
/// happens to be running — a bin folder under Visual Studio, the repo root
/// under <c>dotnet run</c>, or somewhere else entirely under CI.
/// </summary>
public static class Workspace
{
    /// <summary>The file that marks the repository root.</summary>
    private const string Marker = "huddle_src.html";

    private static string? _root;

    /// <summary>
    /// The repository root. Set <c>HB_ROOT</c> to override, otherwise the marker
    /// file is searched for upward from the running assembly and then from the
    /// current directory.
    /// </summary>
    public static string Root => _root ??= Locate();

    /// <summary>Everything generated by a build. Nothing here is edited by hand.</summary>
    public static string Dist => Path.Combine(Root, "dist");

    /// <summary>The static site.</summary>
    public static string Deploy => Path.Combine(Dist, "deploy");

    /// <summary>The paper playbook, field cards and rotation sheet.</summary>
    public static string Print => Path.Combine(Dist, "print");

    /// <summary>The single source file for the app itself.</summary>
    public static string Source => Path.Combine(Root, Marker);

    private static string Locate()
    {
        var fromEnv = Environment.GetEnvironmentVariable("HB_ROOT");
        if (!string.IsNullOrWhiteSpace(fromEnv))
            return Path.GetFullPath(fromEnv);

        foreach (var start in new[] { AppContext.BaseDirectory, Directory.GetCurrentDirectory() })
        {
            for (var dir = new DirectoryInfo(start); dir is not null; dir = dir.Parent)
            {
                if (File.Exists(Path.Combine(dir.FullName, Marker)))
                    return dir.FullName;
            }
        }

        throw new InvalidOperationException(
            $"could not find {Marker} above {AppContext.BaseDirectory} — set HB_ROOT to the repo root");
    }

    /// <summary>Creates a directory if it is not there, and returns it.</summary>
    public static string Ensure(string path)
    {
        Directory.CreateDirectory(path);
        return path;
    }

    /// <summary>
    /// Writes text as UTF-8 with no byte-order mark and no line-ending
    /// translation, which is what every consumer of these files expects.
    /// </summary>
    public static void WriteText(string path, string text) =>
        File.WriteAllBytes(path, new System.Text.UTF8Encoding(false).GetBytes(text));
}
